/**
 * White-label configuration for the UI.
 *
 * The JSON is generated by `make label` from labels/<name>.yaml and committed
 * (resolved freshmart) so a bare `npm run dev` / `vitest` works without Python.
 * It is a projection of the full label -- the seed catalog, synonym list, and
 * agent system prompt are server-side only and never reach the browser.
 *
 * Everything here is display-only. Predicate names, view names, enum values,
 * and wire-format field names are data-model shape and are never rewritten by
 * a label -- `alias*()` changes only what the user reads on screen.
 */
import raw from './generated/label.json'

export interface EntityWords {
  one: string
  many: string
  title?: string
  title_many?: string
  /** Order-number prefix, e.g. "FM-". Only present on `order`. */
  id_prefix?: string
  /** Only present on `perishable`. */
  adjective?: string
  note?: string
  tooltip?: string
  cart_note?: string
}

export interface LabelConfig {
  label: string
  brand: {
    name: string
    tagline: string
    tab_title: string
    theme: { primary: string; accent: string }
    favicon: string
    qr?: { url?: string; cta?: string }
  }
  vocabulary: Record<string, EntityWords>
  enums: Record<string, Record<string, string>>
  aliases: {
    columns: Record<string, string>
    views: Record<string, string>
    predicates: Record<string, string>
  }
  nav: Array<{ path: string; label: string }>
  pages: Record<string, Record<string, string>>
  copy: Record<string, Record<string, string>>
  placeholders: Record<string, string>
  examples: {
    search_queries: string[]
    predicate_values: Record<string, string>
  }
  agent: { persona: string; placeholder?: string; empty_state?: string }
}

export const label = raw as unknown as LabelConfig

export const brand = label.brand
export const navItems = label.nav

/**
 * Which label the container was started with. The *content* above always comes
 * from the generated JSON; this is only for display and for warning when the
 * seeded data was produced by a different label.
 */
export const activeLabelName: string =
  import.meta.env.VITE_DEMO_LABEL || label.label

const warned = new Set<string>()

/** Missing keys can only come from a typo in code, since freshmart.yaml is
 *  exhaustive and every other label merges over it. Make that loud rather than
 *  rendering a silent empty string. */
function missing(path: string): string {
  if (!warned.has(path)) {
    warned.add(path)
    console.warn(`[label] missing key: ${path} (label: ${label.label})`)
  }
  return `⟪${path}⟫`
}

type EntityForm = 'one' | 'many' | 'title' | 'title_many'

/**
 * A display word for an entity type.
 * `entity('order', 'many')` -> "orders" / "claims" / ...
 * Title forms fall back to the lowercase form when a label omits them.
 */
export function entity(type: string, form: EntityForm = 'one'): string {
  const words = label.vocabulary[type]
  if (!words) return missing(`vocabulary.${type}`)
  const direct = words[form]
  if (direct) return direct
  if (form === 'title') return words.one ?? missing(`vocabulary.${type}.one`)
  if (form === 'title_many') return words.many ?? missing(`vocabulary.${type}.many`)
  return missing(`vocabulary.${type}.${form}`)
}

/** Capitalized singular, e.g. "Order" / "Servicing Case". */
export const Entity = (type: string) => entity(type, 'title')
/** Capitalized plural, e.g. "Orders" / "Servicing Cases". */
export const Entities = (type: string) => entity(type, 'title_many')

/**
 * Display label for an internal enum value. The value itself is fixed by the
 * SQL; unknown values pass through unchanged so live data is never hidden.
 */
export function enumLabel(enumName: string, value: string | null | undefined): string {
  if (value === null || value === undefined || value === '') return ''
  return label.enums[enumName]?.[value] ?? value
}

/** Every value of an enum, as {value, label} -- for dropdowns. */
export function enumOptions(enumName: string): Array<{ value: string; label: string }> {
  const map = label.enums[enumName]
  if (!map) {
    missing(`enums.${enumName}`)
    return []
  }
  return Object.entries(map).map(([value, display]) => ({ value, label: display }))
}

/** Display name for a database column / JSON field. Identity by default. */
export const aliasColumn = (name: string): string =>
  label.aliases.columns[name] ?? name

/** Display name for a Materialize view or source. Identity by default. */
export const aliasView = (name: string): string => label.aliases.views[name] ?? name

/** Display name for an ontology predicate. Identity by default. */
export const aliasPredicate = (name: string): string =>
  label.aliases.predicates[name] ?? name

/** A page's string bundle, e.g. `page('orders').title`. */
export function page(key: string): Record<string, string> {
  const bundle = label.pages[key]
  if (!bundle) {
    missing(`pages.${key}`)
    return {}
  }
  return bundle
}

/** One page string with a loud marker if absent. */
export const pageText = (key: string, field: string): string =>
  label.pages[key]?.[field] ?? missing(`pages.${key}.${field}`)

/** A narrative copy block, e.g. `copy('triples').heading`. */
export function copy(key: string): Record<string, string> {
  const bundle = label.copy[key]
  if (!bundle) {
    missing(`copy.${key}`)
    return {}
  }
  return bundle
}

/** One copy string with a loud marker if absent. */
export const copyText = (key: string, field: string): string =>
  label.copy[key]?.[field] ?? missing(`copy.${key}.${field}`)

export const placeholder = (key: string): string =>
  label.placeholders[key] ?? missing(`placeholders.${key}`)

export const searchQueries = label.examples.search_queries

/** Sample value for the "Write a Triple" form, keyed by predicate. */
export const predicateSample = (predicate: string): string =>
  label.examples.predicate_values[predicate] ?? 'value'

/** Nav label for a route, used by tests and the collapsed-sidebar tooltip. */
export const navLabel = (path: string): string =>
  label.nav.find((n) => n.path === path)?.label ?? missing(`nav[${path}]`)

export default label
